// Mocks generated by Mockito 5.0.10 from annotations
// in get_placed/test/features/login/domain/usecases/login_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:get_placed/core/error/failures.dart' as _i5;
import 'package:get_placed/features/login/domain/entites/LoginEntities.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;

import 'login_test.dart' as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeEither<L, R> extends _i1.Fake implements _i2.Either<L, R> {
  @override
  String toString() => super.toString();
}

/// A class which mocks [MockLoginRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockLoginRepository extends _i1.Mock
    implements _i3.MockLoginRepository {
  MockMockLoginRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, bool>> login(_i6.LoginEntities? login) =>
      (super.noSuchMethod(Invocation.method(#login, [login]),
              returnValue: Future<_i2.Either<_i5.Failure, bool>>.value(
                  _FakeEither<_i5.Failure, bool>()))
          as _i4.Future<_i2.Either<_i5.Failure, bool>>);
  @override
  String toString() => super.toString();
}
